# Generated by Django 5.0.6 on 2024-09-13 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='', max_length=500)),
                ('country', models.CharField(choices=[('USA', 'USA'), ('UK', 'UK'), ('Canada', 'Canada'), ('Australia', 'Australia'), ('India', 'India'), ('Bangladesh', 'Bangladesh'), ('China', 'China'), ('Germany', 'Germany'), ('France', 'France'), ('Japan', 'Japan'), ('South Korea', 'South Korea'), ('Brazil', 'Brazil'), ('Mexico', 'Mexico'), ('Russia', 'Russia'), ('Italy', 'Italy'), ('Spain', 'Spain'), ('Netherlands', 'Netherlands'), ('Sweden', 'Sweden'), ('Norway', 'Norway'), ('Denmark', 'Denmark'), ('South Africa', 'South Africa'), ('New Zealand', 'New Zealand'), ('Ireland', 'Ireland'), ('Singapore', 'Singapore'), ('Malaysia', 'Malaysia'), ('Indonesia', 'Indonesia'), ('Philippines', 'Philippines'), ('Pakistan', 'Pakistan'), ('Nigeria', 'Nigeria'), ('Kenya', 'Kenya'), ('Egypt', 'Egypt'), ('Saudi Arabia', 'Saudi Arabia'), ('Turkey', 'Turkey'), ('United Arab Emirates', 'United Arab Emirates'), ('Argentina', 'Argentina'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Venezuela', 'Venezuela'), ('Israel', 'Israel'), ('Poland', 'Poland'), ('Greece', 'Greece'), ('Portugal', 'Portugal'), ('Finland', 'Finland'), ('Switzerland', 'Switzerland'), ('Austria', 'Austria'), ('Belgium', 'Belgium'), ('Czech Republic', 'Czech Republic'), ('Hungary', 'Hungary'), ('Romania', 'Romania'), ('Ukraine', 'Ukraine'), ('Vietnam', 'Vietnam'), ('Thailand', 'Thailand'), ('Sri Lanka', 'Sri Lanka'), ('Nepal', 'Nepal')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
