# Generated by Django 5.0.6 on 2024-09-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
