# Generated by Django 5.0.6 on 2024-09-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_category_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attachments',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
