# Generated by Django 5.0.6 on 2024-09-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attachments',
            field=models.CharField(default='', max_length=500),
        ),
    ]
