# Generated by Django 5.0.6 on 2024-09-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='rating',
            field=models.CharField(blank=True, choices=[('✩', '✩'), ('✩✩', '✩✩'), ('✩✩✩', '✩✩✩'), ('✩✩✩✩', '✩✩✩✩'), ('✩✩✩✩✩', '✩✩✩✩✩')], default=('✩', '✩'), max_length=5),
        ),
    ]
