# Generated by Django 5.0.6 on 2024-09-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_alter_freelancer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='image',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
