# Generated by Django 5.0.6 on 2024-09-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_alter_freelancer_image_alter_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='rating',
            field=models.CharField(blank=True, choices=[('✩', '✩'), ('✩✩', '✩✩'), ('✩✩✩', '✩✩✩'), ('✩✩✩✩', '✩✩✩✩'), ('✩✩✩✩✩', '✩✩✩✩✩')], default=('✩', '✩'), max_length=500),
        ),
    ]
